spring:
  datasource:
    url: jdbc:mysql://${DB_DEV_HOST}:${DB_DEV_PORT}/${DB_DEV_NAME}
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASSWORD}

security:
  jwt:
    secret-key: ${JWT_DEV_SECRET}

server:
  port: ${PORT:8080}
